sudo: required
services:
  - docker

before_install:
  - docker b uild -t mikecoys/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mikecoys/react-test npm run test -- --coverage

after_success:
  - docker build -t mikecoys/multi-client ./client
  - docker build -t mikecoys/multi-nginx ./nginx
  - docker build -t mikecoys/multi-server ./server
  - docker build -t mikecoys/multi-worker ./worker
  # Setup env vars in travis settings with the user login credentials
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mikecoys/multi-client
  - docker push mikecoys/multi-nginx
  - docker push mikecoys/multi-server
  - docker push mikecoys/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-052049757314
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
